package Entidades;
// Generated 02/01/2017 14:09:58 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor")
public class Doctor  implements java.io.Serializable {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
     private int iddoctor;
@OneToOne
@JoinColumn(name = "iduser")
     private Usuario usuario;
     private String nick;
     private String pass;
     private String email;
@OneToMany(mappedBy = "doctor")
     private List<Historialclinico>ListaHistorial = new ArrayList<>();

    public Doctor() {    
    }

    public int getIddoctor() {
        return iddoctor;
    }

    public void setIddoctor(int iddoctor) {
        this.iddoctor = iddoctor;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<Historialclinico> getListaHistorial() {
        return ListaHistorial;
    }

    public void setListaHistorial(List<Historialclinico> ListaHistorial) {
        this.ListaHistorial = ListaHistorial;
    }
   
}