package Entidades;
// Generated 02/01/2017 14:09:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Historialclinico generated by hbm2java
 */
@Entity
@Table(name = "historialclinico")
public class Historialclinico  implements java.io.Serializable {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
     private int idhistorial;
@ManyToOne
@JoinColumn(name = "iddoctor")
     private Doctor doctor;
@ManyToOne
@JoinColumn(name = "idpaciente")
     private Paciente paciente;
     private Date fechhist;
     private Date fechanthist;
     private Date fechproxhist;
     private String observacion;

    public Historialclinico() {
    }

    public int getIdhistorial() {
        return idhistorial;
    }

    public void setIdhistorial(int idhistorial) {
        this.idhistorial = idhistorial;
    }

    public Doctor getDoctor() {
        return doctor;
    }

    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    public Paciente getPaciente() {
        return paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    public Date getFechhist() {
        return fechhist;
    }

    public void setFechhist(Date fechhist) {
        this.fechhist = fechhist;
    }

    public Date getFechanthist() {
        return fechanthist;
    }

    public void setFechanthist(Date fechanthist) {
        this.fechanthist = fechanthist;
    }

    public Date getFechproxhist() {
        return fechproxhist;
    }

    public void setFechproxhist(Date fechproxhist) {
        this.fechproxhist = fechproxhist;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }	

}