package Entidades;
// Generated 02/01/2017 14:09:58 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente")
public class Paciente  implements java.io.Serializable {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
     private int idpaciente;
@OneToOne
@JoinColumn(name = "iduser")
     private Usuario usuario;
     private String motivoconsulta;
     
@OneToMany(mappedBy = "paciente")
     private List<Historialclinico> HistorialclinicosPaciente = new ArrayList<>();

    public Paciente() {
    }

    public int getIdpaciente() {
        return idpaciente;
    }

    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getMotivoconsulta() {
        return motivoconsulta;
    }

    public void setMotivoconsulta(String motivoconsulta) {
        this.motivoconsulta = motivoconsulta;
    }

    public List<Historialclinico> getHistorialclinicosPaciente() {
        return HistorialclinicosPaciente;
    }

    public void setHistorialclinicosPaciente(List<Historialclinico> HistorialclinicosPaciente) {
        this.HistorialclinicosPaciente = HistorialclinicosPaciente;
    }
    
}